### ISSUE TITLE
not working on godot 4 beta

### ISSUE THREAD

**Issue by pooyapower** [HK-SHAO/Godot-RayTracing-Demo#2]
i downloaded and run it.
but unfortunately it's not working on godot 4 beta 14.
can you fix it ?

**Comment by HK-SHAO** [comment]
no problem, please wait for me the morning after

**Comment by HK-SHAO** [comment]
Now it runs well in v4.0.beta16.official [518b9e580]
After importing the project, you may need to reload the current project once

**Comment by pooyapower** [comment]
thank u
